### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jeizenga** [vgteam/vg_docker#7]
@mlin 
I've been told you're the person to talk to about a problem I'm having. I'm getting a build error that may make sense to you but is mysterious to me. The commit in VG that this is based on passed VG Travis and VG Jenkins.
https://travis-ci.org/vgteam/vg_docker

The failing command seems to be here:
https://github.com/vgteam/vg_docker/blob/master/Dockerfile.build#L53

Do you have any pointers on how I could debug this?

**Comment by mlin** [comment]
@jeizenga sometimes you really have to dig through the travis log because of how a bunch of build processes are running in parallel. On line 4360, I see `/bin/bash: gawk: command not found`. So maybe try adding gawk to the list of apt packages installed in that Dockerfile.build.

**Comment by mlin** [comment]
@jeizenga @glennhickey Looks like this worked, right?
